In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/Taj1920/Data-Analysis-Datasets/refs/heads/main/Datasets-Practice/flipkart_sales.csv')
df

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating
0,ORD00001,Educational Book,Books,49069.56,2,98139.12,2024-09-12,Debit Card,3.5
1,ORD00002,Jeans,Clothing,12755.85,4,51023.40,2024-12-18,UPI,3.9
2,ORD00003,Face Cream,Beauty,11092.19,4,44368.76,2024-05-18,Debit Card,4.4
3,ORD00004,Smartwatch,Electronics,32657.81,1,32657.81,2024-11-08,Debit Card,3.2
4,ORD00005,Cookware Set,Home & Kitchen,26590.08,3,79770.24,2024-12-27,UPI,3.1
...,...,...,...,...,...,...,...,...,...
995,ORD00996,Smartphone,Electronics,28995.81,3,86987.43,2025-01-13,COD,5.0
996,ORD00997,Perfume,Beauty,32799.51,2,65599.02,2024-12-18,Wallet,2.4
997,ORD00998,Face Cream,Beauty,40840.80,1,40840.80,2024-07-26,UPI,3.1
998,ORD00999,Cookware Set,Home & Kitchen,34741.79,4,138967.16,2024-10-02,Net Banking,3.2
999,ORD01000,Table Lamp,Home & Kitchen,16698.12,4,66792.48,2024-03-26,Credit Card,1.6

```
1.Calculate total sales for each product.
Group by ProductName and sum TotalSales (INR).

```

In [3]:
total_sales = df.groupby('Product Name')['Total Sales (INR)'].sum().reset_index().sort_values(by='Total Sales (INR)', ascending=False).head()
total_sales  #descending form converted

        Product Name  Total Sales (INR)
5   Educational Book         4522055.35
12            Laptop         4132783.72
23        Table Lamp         3986691.68
9         Headphones         3722765.27
11             Jeans         3685259.60

```
2. Find the average customer rating for each category.
Group by Category and take mean of Customer Rating

```

In [4]:
df.groupby('Category')['Customer Rating'].mean()

Category
Beauty            2.872396
Books             3.079904
Clothing          2.971429
Electronics       2.988479
Home & Kitchen    3.138860
Name: Customer Rating, dtype: float64

```
3. Find the total quantity sold per category.
Group by Category and sum QuantitySold.

```

In [5]:
df.groupby('Category')['Quantity Sold'].sum()

Category
Beauty            583
Books             653
Clothing          609
Electronics       673
Home & Kitchen    579
Name: Quantity Sold, dtype: int64

```
4. Find the highest-selling product based on total sales.
Group by ProductName → sum → sort.

```

In [6]:
highest_product = df.groupby('Product Name')['Total Sales (INR)'].sum().sort_values(ascending=False).head(1)

print(highest_product)

Product Name
Educational Book    4522055.35
Name: Total Sales (INR), dtype: float64

`5.Count how many orders were paid with each payment method
Group by PaymentMethod and count Order ID.
`

In [7]:
df  #show dataset

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating
0,ORD00001,Educational Book,Books,49069.56,2,98139.12,2024-09-12,Debit Card,3.5
1,ORD00002,Jeans,Clothing,12755.85,4,51023.40,2024-12-18,UPI,3.9
2,ORD00003,Face Cream,Beauty,11092.19,4,44368.76,2024-05-18,Debit Card,4.4
3,ORD00004,Smartwatch,Electronics,32657.81,1,32657.81,2024-11-08,Debit Card,3.2
4,ORD00005,Cookware Set,Home & Kitchen,26590.08,3,79770.24,2024-12-27,UPI,3.1
...,...,...,...,...,...,...,...,...,...
995,ORD00996,Smartphone,Electronics,28995.81,3,86987.43,2025-01-13,COD,5.0
996,ORD00997,Perfume,Beauty,32799.51,2,65599.02,2024-12-18,Wallet,2.4
997,ORD00998,Face Cream,Beauty,40840.80,1,40840.80,2024-07-26,UPI,3.1
998,ORD00999,Cookware Set,Home & Kitchen,34741.79,4,138967.16,2024-10-02,Net Banking,3.2
999,ORD01000,Table Lamp,Home & Kitchen,16698.12,4,66792.48,2024-03-26,Credit Card,1.6

In [8]:
df['Payment Method'].value_counts()   #value_counts() see the effect

Payment Method
UPI            176
Wallet         172
Debit Card     171
COD            169
Net Banking    166
Credit Card    146
Name: count, dtype: int64

In [9]:
payment_counts = df.groupby('Payment Method')['Order ID'].count().reset_index() #difference between with reset_indec()

print(payment_counts)

  Payment Method  Order ID
0            COD       169
1    Credit Card       146
2     Debit Card       171
3    Net Banking       166
4            UPI       176
5         Wallet       172

In [10]:
payment_counts = df.groupby('Payment Method')['Order ID'].count()

print(payment_counts)

Payment Method
COD            169
Credit Card    146
Debit Card     171
Net Banking    166
UPI            176
Wallet         172
Name: Order ID, dtype: int64

```
6. Determine the average price of products in each category.
Group by Category and take mean of Price(INR).
```

In [11]:
avg_price = df.groupby('Category', as_index=False)['Price (INR)'].mean()

print(avg_price)

         Category   Price (INR)
0          Beauty  24610.456615
1           Books  23342.025455
2        Clothing  25185.978519
3     Electronics  25824.873134
4  Home & Kitchen  23587.667668

```
7. Calculate monthly sales (group by month of Order Date).
Extract month → group by month → sum TotalSales (INR).

```

In [12]:
df['Order Date'] = pd.to_datetime(df['Order Date'])

monthly_sales = df.groupby(
    df['Order Date'].dt.to_period('M')
)['Total Sales (INR)'].sum()

print(monthly_sales)

Order Date
2024-02    3910477.01
2024-03    6508879.04
2024-04    7334962.92
2024-05    6706004.97
2024-06    4992364.75
2024-07    7637324.95
2024-08    5418893.98
2024-09    6264222.31
2024-10    5702923.37
2024-11    5578535.08
2024-12    6491639.99
2025-01    7160788.17
2025-02    1506096.20
Freq: M, Name: Total Sales (INR), dtype: float64

```
8. Find the total sales per payment method.
Group by PaymentMethod and sum TotalSales (INR).

```

In [13]:
df.groupby('Payment Method', as_index=False)['Total Sales (INR)'].sum()

  Payment Method  Total Sales (INR)
0            COD        12457136.55
1    Credit Card        11155785.99
2     Debit Card        12142559.04
3    Net Banking        13219947.52
4            UPI        12790919.48
5         Wallet        13446764.16

```
9. Get the number of unique products sold in each category.
Group by Category and apply nunique() on ProductName.

```

In [14]:
df.groupby('Category', as_index=False)['Product Name'].nunique()

         Category  Product Name
0          Beauty             5
1           Books             5
2        Clothing             5
3     Electronics             5
4  Home & Kitchen             5

```
10. Find the average quantity sold per order for each product.
Group by ProductName and take mean of QuantitySold.

```

In [15]:
df.groupby('Product Name', as_index=False)['Quantity Sold'].mean()

        Product Name  Quantity Sold
0           Bedsheet       2.966667
1         Comic Book       3.076923
2           Cookbook       3.172414
3       Cookware Set       3.000000
4              Dress       3.448276
5   Educational Book       2.937500
6         Face Cream       3.263158
7      Fiction Novel       3.365854
8         Hair Dryer       3.000000
9         Headphones       3.068182
10            Jacket       3.184211
11             Jeans       3.142857
12            Laptop       3.250000
13          Lipstick       3.045455
14     Mixer Grinder       3.083333
15           Perfume       3.125000
16    Self-Help Book       3.194444
17           Shampoo       2.705882
18        Smartphone       3.075000
19        Smartwatch       2.914894
20          Sneakers       3.205128
21        Sofa Cover       2.878049
22           T-Shirt       3.195122
23        Table Lamp       3.065217
24            Tablet       3.210526

```
11. Identify which category has the highest average total sales per order.
Group by Category → mean of TotalSales (INR).

```

In [16]:
df.groupby('Category')['Total Sales (INR)'].mean().sort_values(ascending=False)

Category
Clothing          79970.300847
Electronics       79756.557926
Beauty            76461.375260
Books             70745.261483
Home & Kitchen    69042.534249
Name: Total Sales (INR), dtype: float64

```
12. Get the maximum total sales order for each date.
Group by Order Date and find max(TotalSales).

```

In [17]:
df.groupby('Order Date', as_index=False)['Total Sales (INR)'].max()

    Order Date  Total Sales (INR)
0   2024-02-12           47666.18
1   2024-02-13          102071.88
2   2024-02-14          139601.00
3   2024-02-15          237678.95
4   2024-02-17          143690.56
..         ...                ...
341 2025-02-05           51604.35
342 2025-02-06           37295.08
343 2025-02-07          143284.64
344 2025-02-08          232047.85
345 2025-02-09           27204.69

[346 rows x 2 columns]

```
13. For each payment method, find the average customer rating.
Group by PaymentMethod and mean of Customer Rating.

```

In [18]:
df.groupby('Payment Method', as_index=False)['Customer Rating'].mean()

  Payment Method  Customer Rating
0            COD         2.976331
1    Credit Card         3.119178
2     Debit Card         3.013450
3    Net Banking         2.943373
4            UPI         3.071591
5         Wallet         2.954651

```
14. For each category, calculate min, max, and average quantity sold.
Group by Category and aggregate with [min, max, mean].

```

In [19]:
df.groupby('Category')['Quantity Sold'].agg(['min', 'max', 'mean'])

                min  max      mean
Category
Beauty            1    5  3.036458
Books             1    5  3.124402
Clothing          1    5  3.222222
Electronics       1    5  3.101382
Home & Kitchen    1    5  3.000000

```
15. Calculate total revenue per day and find the day with highest sales.
Group by Order Date → sum TotalSales.

```

In [20]:
df.groupby('Order Date')['Total Sales (INR)'].sum().sort_values(ascending=False).head(1)

Order Date
2024-03-30    1093950.44
Name: Total Sales (INR), dtype: float64

```
16. Find which product has the highest average customer rating.
Group by ProductName → mean(Customer Rating).

```

In [21]:
df.groupby('Product Name')['Customer Rating'].mean().sort_values(ascending=False).head(1)

Product Name
Bedsheet    3.713333
Name: Customer Rating, dtype: float64


```
19. For each category, find the top-selling product (highest total sales).
Group by Category + ProductName.

```

In [22]:
df['Category'].unique()

array(['Books', 'Clothing', 'Beauty', 'Electronics', 'Home & Kitchen'],
      dtype=object)

In [23]:
cat=df.groupby('Category')
Books=cat.get_group('Books')
Clothing=cat.get_group('Clothing')
Beauty=cat.get_group('Beauty')
Electronics=cat.get_group('Electronics')
Home=cat.get_group('Home & Kitchen')

In [24]:
df.groupby(['Category', 'Product Name'])['Total Sales (INR)'].sum().reset_index().sort_values('Total Sales (INR)', ascending=False).groupby('Category').head(1)

          Category      Product Name  Total Sales (INR)
7            Books  Educational Book         4522055.35
16     Electronics            Laptop         4132783.72
24  Home & Kitchen        Table Lamp         3986691.68
12        Clothing             Jeans         3685259.60
0           Beauty        Face Cream         3646816.97

In [25]:
Books.groupby('Product Name')['Total Sales (INR)'].sum().reset_index().sort_values('Total Sales (INR)', ascending=False).head(1)

       Product Name  Total Sales (INR)
2  Educational Book         4522055.35

In [26]:
Clothing.groupby('Product Name')['Total Sales (INR)'].sum().reset_index().sort_values('Total Sales (INR)', ascending=False).head(1)

  Product Name  Total Sales (INR)
2        Jeans          3685259.6

In [27]:
Beauty.groupby('Product Name')['Total Sales (INR)'].sum().reset_index().sort_values('Total Sales (INR)', ascending=False).head(1)

  Product Name  Total Sales (INR)
0   Face Cream         3646816.97

In [28]:
Electronics.groupby('Product Name')['Total Sales (INR)'].sum().reset_index().sort_values('Total Sales (INR)', ascending=False).head(1)

  Product Name  Total Sales (INR)
1       Laptop         4132783.72

In [29]:
Home.groupby('Product Name')['Total Sales (INR)'].sum().reset_index().sort_values('Total Sales (INR)', ascending=False).head(1)

  Product Name  Total Sales (INR)
4   Table Lamp         3986691.68

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order ID           1000 non-null   object
 1   Product Name       1000 non-null   object
 2   Category           1000 non-null   object
 3   Price (INR)        1000 non-null   float64
 4   Quantity Sold      1000 non-null   int64
 5   Total Sales (INR)  1000 non-null   float64
 6   Order Date         1000 non-null   datetime64[ns]
 7   Payment Method     1000 non-null   object
 8   Customer Rating    1000 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(4)
memory usage: 70.4+ KB

In [31]:
pd.to_datetime(df['Order Date'])

0     2024-09-12
1     2024-12-18
2     2024-05-18
3     2024-11-08
4     2024-12-27
         ...
995   2025-01-13
996   2024-12-18
997   2024-07-26
998   2024-10-02
999   2024-03-26
Name: Order Date, Length: 1000, dtype: datetime64[ns]

In [32]:
df['Order Date']=pd.to_datetime(df['Order Date'])  # assign

In [33]:
df['Order Date'].dt.month

0       9
1      12
2       5
3      11
4      12
       ..
995     1
996    12
997     7
998    10
999     3
Name: Order Date, Length: 1000, dtype: int32

In [34]:
df['Order Date'].dt.year

0      2024
1      2024
2      2024
3      2024
4      2024
       ...
995    2025
996    2024
997    2024
998    2024
999    2024
Name: Order Date, Length: 1000, dtype: int32

In [35]:
df['month']=df['Order Date'].dt.month

In [36]:
df.groupby('month')['Total Sales (INR)'].sum()

month
1     7160788.17
2     5416573.21
3     6508879.04
4     7334962.92
5     6706004.97
6     4992364.75
7     7637324.95
8     5418893.98
9     6264222.31
10    5702923.37
11    5578535.08
12    6491639.99
Name: Total Sales (INR), dtype: float64

In [37]:
pd.to_datetime(df['Order Date'],format='mixed',errors='coerce',dayfirst=True)

0     2024-09-12
1     2024-12-18
2     2024-05-18
3     2024-11-08
4     2024-12-27
         ...
995   2025-01-13
996   2024-12-18
997   2024-07-26
998   2024-10-02
999   2024-03-26
Name: Order Date, Length: 1000, dtype: datetime64[ns]

In [38]:
df['Order Date']=pd.to_datetime(df['Order Date'],format='mixed',errors='coerce',dayfirst=True)

In [39]:
df['month']=df['Order Date'].dt.month_name()  #only monthly display

In [40]:
df.groupby('month')['Total Sales (INR)'].sum()

month
April        7334962.92
August       5418893.98
December     6491639.99
February     5416573.21
January      7160788.17
July         7637324.95
June         4992364.75
March        6508879.04
May          6706004.97
November     5578535.08
October      5702923.37
September    6264222.31
Name: Total Sales (INR), dtype: float64

**Concatenation- its used to merge two different dataframe**

In [41]:
df1=pd.DataFrame({'name':['A','B','C','D','np.Nan'],
                  'age' :[10,11,12,13,14]})
df2=pd.DataFrame({'name':['A','B','C','E','np.NaN'],
                  'marks' :[87,97,25,66,12]})

In [42]:
df2

     name  marks
0       A     87
1       B     97
2       C     25
3       E     66
4  np.NaN     12

**Vertical Concatenation- Its used to concatenate the dataframe row by row**

In [43]:
pd.concat([df1,df2])  #so many Null values

     name   age  marks
0       A  10.0    NaN
1       B  11.0    NaN
2       C  12.0    NaN
3       D  13.0    NaN
4  np.Nan  14.0    NaN
0       A   NaN   87.0
1       B   NaN   97.0
2       C   NaN   25.0
3       E   NaN   66.0
4  np.NaN   NaN   12.0

**Horizontal Concatenation- its used to concatenate the dataframe column by column**

In [44]:
pd.concat([df1,df2],axis=1)  #duplicate column has been created

     name  age    name  marks
0       A   10       A     87
1       B   11       B     97
2       C   12       C     25
3       D   13       E     66
4  np.Nan   14  np.NaN     12

**Join- Its used to merge the two different dataframe based on the common columns**

**Inner Join**

In [45]:
df1.merge(df2, how='inner',on='name')

  name  age  marks
0    A   10     87
1    B   11     97
2    C   12     25

In [46]:
df1.merge(df2, how='left',on='name')  #common data and left data

     name  age  marks
0       A   10   87.0
1       B   11   97.0
2       C   12   25.0
3       D   13    NaN
4  np.Nan   14    NaN

In [47]:
df1.merge(df2, how='right',on='name')

     name   age  marks
0       A  10.0     87
1       B  11.0     97
2       C  12.0     25
3       E   NaN     66
4  np.NaN   NaN     12

In [48]:
df1.merge(df2, how='outer',on='name')

     name   age  marks
0       A  10.0   87.0
1       B  11.0   97.0
2       C  12.0   25.0
3       D  13.0    NaN
4       E   NaN   66.0
5  np.NaN   NaN   12.0
6  np.Nan  14.0    NaN

**apply function- is used to apply a function to every value (or row/column) in a Pandas Series or DataFrame.**

In [49]:
df['Quantity Sold'].apply(lambda x:x*2)   #1 format- apply function :more flexibility

0      4
1      8
2      8
3      2
4      6
      ..
995    6
996    4
997    2
998    8
999    8
Name: Quantity Sold, Length: 1000, dtype: int64

In [50]:
df['Quantity Sold']*2    #2 format, less fexibility

0      4
1      8
2      8
3      2
4      6
      ..
995    6
996    4
997    2
998    8
999    8
Name: Quantity Sold, Length: 1000, dtype: int64

In [51]:
#3 format
def fun(n):
    return n**2
df['Quantity Sold'].apply(fun)

0       4
1      16
2      16
3       1
4       9
       ..
995     9
996     4
997     1
998    16
999    16
Name: Quantity Sold, Length: 1000, dtype: int64

In [52]:
l=[1,2,3,4]
list(map(lambda x:x*2,l))

[2, 4, 6, 8]


```
Pivot table- its known as powerhouse of pandas because its used to do perform multiple aggregation function on multiple columns based on the given category.
syntax= df.pivot_table(['col1','col2',....,'coln'],index='categorical column',aggfunc=['func1','fun2'*,'fun n'])

```

In [53]:
df.pivot_table(['Total Sales (INR)','Customer Rating'],index='Category',aggfunc=['sum','max','mean'])

                           sum                               max  \
               Customer Rating Total Sales (INR) Customer Rating
Category
Beauty                   551.5       14680584.05             5.0
Books                    643.7       14785759.65             5.0
Clothing                 561.6       15114386.86             4.9
Electronics              648.5       17307173.07             5.0
Home & Kitchen           605.8       13325209.11             5.0

                                            mean
               Total Sales (INR) Customer Rating Total Sales (INR)
Category
Beauty                 243903.90        2.872396      76461.375260
Books                  237136.50        3.079904      70745.261483
Clothing               240653.00        2.971429      79970.300847
Electronics            233850.05        2.988479      79756.557926
Home & Kitchen         236422.70        3.138860      69042.534249

**Slicing- Slicing means selecting a specific range of rows or columns from a DataFrame.**

In [54]:
df.loc[0:10, ['Product Name','Price (INR)','Order Date']]  #.loc[] is used to select specific rows and columns from a DataFrame using their labels.

        Product Name  Price (INR) Order Date
0   Educational Book     49069.56 2024-09-12
1              Jeans     12755.85 2024-12-18
2         Face Cream     11092.19 2024-05-18
3         Smartwatch     32657.81 2024-11-08
4       Cookware Set     26590.08 2024-12-27
5      Mixer Grinder     10475.03 2024-10-22
6           Sneakers     38647.72 2024-07-04
7         Table Lamp     24818.59 2024-12-27
8             Jacket      1987.39 2025-01-18
9             Tablet     26876.51 2024-03-14
10           Perfume     46409.57 2025-02-08

In [55]:
df.iloc[0:10,4:6] #ending indexing is not included, no need to mentioned column name
#.iloc[] = position-based indexing

   Quantity Sold  Total Sales (INR)
0              2           98139.12
1              4           51023.40
2              4           44368.76
3              1           32657.81
4              3           79770.24
5              2           20950.06
6              3          115943.16
7              3           74455.77
8              2            3974.78
9              2           53753.02